# Generated by Django 2.2 on 2020-07-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='diary_completed',
        ),
        migrations.AddField(
            model_name='diary',
            name='diary_slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='diary_editor',
            field=models.TextField(),
        ),
    ]
