# Generated by Django 2.2 on 2020-07-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20200723_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='diary_slug',
        ),
    ]
