# Generated by Django 2.2 on 2020-07-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_remove_diary_diary_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='diary_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
