# Generated by Django 2.2 on 2020-07-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_diary_diary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='diary_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='diary',
            name='diary_image',
            field=models.ImageField(blank=True, null=True, upload_to='landingpage/static/images'),
        ),
    ]
