# Generated by Django 2.2 on 2020-07-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_auto_20200726_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='diary_image',
        ),
    ]
