# Generated by Django 2.2 on 2020-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_remove_diary_diary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
